#!/bin/bash

# Test script for file explorer refresh after file operations
# This script provides manual testing steps

echo "🧪 Testing File Explorer Auto-Refresh After File Operations"
echo "=========================================================="
echo ""
echo "Prerequisites:"
echo "1. Start the RCode server: go run main.go"
echo "2. Login and create a session"
echo "3. Open browser console to see debug logs"
echo ""
echo "Test Cases:"
echo ""
echo "1. Write File Test:"
echo "   - Send: 'Create a new file test1.txt with content Hello World'"
echo "   - Expected:"
echo "     a) Files tab auto-switches on first response"
echo "     b) Console shows: 'Auto-switching to Files tab on first response'"
echo "     c) Console shows: 'Tool usage event received:' with write_file"
echo "     d) Console shows: 'File operation detected, refreshing file tree for tool: write_file'"
echo "     e) Console shows: 'Refreshing file tree now...'"
echo "     f) File tree updates to show test1.txt"
echo ""
echo "2. Edit File Test:"
echo "   - Send: 'Edit test1.txt and add a second line saying Goodbye'"
echo "   - Expected:"
echo "     a) Files tab remains active (already on Files)"
echo "     b) Console shows tool usage for edit_file"
echo "     c) File tree refreshes after edit operation"
echo ""
echo "3. Create Directory Test:"
echo "   - Send: 'Create a new directory called test_folder'"
echo "   - Expected:"
echo "     a) Console shows tool usage for make_dir"
echo "     b) File tree refreshes showing new directory"
echo ""
echo "4. Move File Test:"
echo "   - Send: 'Move test1.txt into test_folder'"
echo "   - Expected:"
echo "     a) Console shows tool usage for move"
echo "     b) File tree refreshes showing file in new location"
echo ""
echo "5. Remove File Test:"
echo "   - Send: 'Delete the file test_folder/test1.txt'"
echo "   - Expected:"
echo "     a) Console shows tool usage for remove"
echo "     b) File tree refreshes, file disappears"
echo ""
echo "6. Multiple Operations Test:"
echo "   - Send: 'Create files a.txt, b.txt, and c.txt with different content'"
echo "   - Expected:"
echo "     a) Multiple tool_usage events for write_file"
echo "     b) File tree refreshes after each operation"
echo "     c) All files appear in the tree"
echo ""
echo "Console Verification Checklist:"
echo "✓ Check for 'Tool usage event received:' messages"
echo "✓ Verify tool names match the operations (write_file, edit_file, etc.)"
echo "✓ Look for 'File operation detected, refreshing file tree for tool:' messages"
echo "✓ Confirm 'Refreshing file tree now...' appears after 200ms delay"
echo "✓ Watch network tab for /api/files/tree requests after operations"
echo ""
echo "Debugging Commands:"
echo "In browser console, you can manually test:"
echo "  window.FileExplorer.loadFileTree()  // Manual refresh"
echo "  window.FileExplorer.switchTab('files')  // Manual tab switch"
echo ""
echo "Known File Tools:"
echo "- write_file"
echo "- edit_file"
echo "- make_dir"
echo "- remove"
echo "- move"