#!/bin/bash

# Test script for auto-switch to Files tab functionality
# This script provides manual testing steps

echo "🧪 Testing Auto-Switch to Files Tab on First LLM Response"
echo "========================================================"
echo ""
echo "Prerequisites:"
echo "1. Start the RCode server: go run main.go"
echo "2. Login and create a session"
echo "3. Make sure you're on the Sessions tab initially"
echo ""
echo "Test Cases:"
echo ""
echo "1. Basic Text Response Test:"
echo "   - Ensure you're on the Sessions tab"
echo "   - Send: 'Hello, can you help me understand Go?'"
echo "   - Expected: Files tab automatically activates when response starts"
echo "   - Verify: Console shows 'Auto-switching to Files tab on first response'"
echo ""
echo "2. Tool Execution Test:"
echo "   - Switch back to Sessions tab manually"
echo "   - Send: 'Please create a file test.txt with hello world'"
echo "   - Expected: Files tab activates when tool execution starts"
echo "   - Verify: You see the file operation in the Files tab"
echo ""
echo "3. Multiple Responses Test:"
echo "   - Stay on Files tab after first response"
echo "   - Continue the conversation"
echo "   - Expected: Tab doesn't switch again for subsequent responses"
echo ""
echo "4. New Message Test:"
echo "   - Manually switch to Sessions tab"
echo "   - Send a new message"
echo "   - Expected: Files tab activates again for the new message's first response"
echo ""
echo "5. Session Switching Test:"
echo "   - Create a new session"
echo "   - Send a message in the new session"
echo "   - Expected: Files tab activates for the new session's first response"
echo ""
echo "Console Verification:"
echo "✓ Look for 'Auto-switching to Files tab on first response' in browser console"
echo "✓ Verify hasReceivedFirstResponse flag resets on new messages"
echo "✓ Check that FileExplorer.switchTab is available in console"
echo ""
echo "Manual Console Test:"
echo "You can test the switchTab function manually in browser console:"
echo "  window.FileExplorer.switchTab('sessions')"
echo "  window.FileExplorer.switchTab('files')"
echo "  window.FileExplorer.switchTab('tools')"